### ISSUE TITLE
输完验证码后无反应

### ISSUE THREAD

**Issue by nianyu1** [cc004/pcrjjc2#101]
![$}{(LU E){C 31U7~BK H}G](https://user-images.githubusercontent.com/86151210/185510932-1e837ae6-e72a-4b5b-9e10-08b56586793f.png)
只要帐号会跳验证码，无论输不输验证码都会跳这个错误，竞技场查询一开始会没反应后面出现风控，大佬这个问题怎么解决呀？

**Comment by cc004** [comment]
这个错误意味着绑人过多不能在查询间隔内全部完成

**Comment by cc004** [comment]
也有可能是无验证码导致卡死

**Comment by nianyu1** [comment]
那具体怎么解决呢，我正常指令输入验证码后依旧无法解决
![% MR%HKMDK1{ SN0%)DEPAG](https://user-images.githubusercontent.com/86151210/185513051-050d2537-1de6-411a-8373-8417305942d7.png)

**Comment by cc004** [comment]
如果竞技场查询指令可以用的话把轮询间隔调长或者不管也行

**Comment by nianyu1** [comment]
第一次输入跳验证码，然后我正常指令输入验证码后，一段时间内输入竞技场查询无反应无回复，只有那个跳错。过了这段时间后，输入竞技场查询会出现
![image](https://user-images.githubusercontent.com/86151210/185597708-d3451884-f8e9-4013-9746-9e5696fa3aa8.png)

**Comment by cc004** [comment]
试试把定时任务关了然后jjc查询

**Comment by nianyu1** [comment]
大佬，不太会，怎么关定时任务😂

**Comment by cc004** [comment]
代码里找schedule 注释掉整个函数
我寻思控制台没报错吗

**Comment by nianyu1** [comment]
注释掉整个函数schedule会报错。。。

**Comment by cc004** [comment]
截图你改的和报错

**Comment by nianyu1** [comment]
![image](https://user-images.githubusercontent.com/86151210/185770921-cd0d6d4e-9945-4fdb-9fba-779b576f3f84.png)
![image](https://user-images.githubusercontent.com/86151210/185770936-e15e08a2-523f-4962-b613-a654a7bb1654.png)
![image](https://user-images.githubusercontent.com/86151210/185770943-2f1b00c1-a96c-4286-9d8a-fc2285d1be5b.png)
![image](https://user-images.githubusercontent.com/86151210/185770946-4614b04d-deb4-433a-8e3f-a134318be6df.png)

**Comment by cc004** [comment]
注释掉整个函数不是函数签名

**Comment by nianyu1** [comment]
![image](https://user-images.githubusercontent.com/86151210/185771119-7a142522-9bea-4ea1-9cb4-505b6a0d3c3c.png)
输入完验证码后再次竞技场查询无反应

**Comment by cc004** [comment]
看看version.txt

**Comment by nianyu1** [comment]
![image](https://user-images.githubusercontent.com/86151210/185771215-ccdff4e7-8dd3-4eed-b4ab-6d084a5cb31a.png)
![image](https://user-images.githubusercontent.com/86151210/185771221-7db95842-90ea-46aa-8f3d-84652f350175.png)
文件夹里不生成version.txt

**Comment by cc004** [comment]
换个号吧。。。。

**Comment by nianyu1** [comment]
手登app都无输入验证码，就是这回版本更新后py突然要输验证码😂之前只要弹验证码的，就没成功一次，输入验证码后续没响应了

**Comment by cc004** [comment]
应该是你号因为其他原因b站登陆失败，重复登录触发风控
