### ISSUE TITLE
突然就报这个错了

### ISSUE THREAD

**Issue by WindStill** [cc004/pcrjjc2#103]
之前好好的

`Execution of job "SafeService.decoWrapper.<locals>.wrapper (trigger: interval[0:01:00], next run at: 2022-10-28 14:28:04 CST)" skipped: maximum number of running instances reached (1)`

**Comment by cc004** [comment]
不是报错 意味着你下次轮询时上次轮询还在执行中

**Comment by WindStill** [comment]
> 不是报错 意味着你下次轮询时上次轮询还在执行中

这个要做什么设置，是我的网络问题吗，现在只绑定了一个竞技场账号。而且单独的『竞技场查询』也不出结果

**Comment by WindStill** [comment]
没有其他任何报错，但是就是不推送，查询也不出结果。
2021.10.14版本、最新版本都是这个问题

**Comment by WindStill** [comment]
应该是封控了，手机登录账号需要验证码。
但是机器人没有发送验证码的链接

**Comment by clacknya** [comment]
这几天阿b改了验证的策略，基本每次调用登录都要验证了

**Comment by clacknya** [comment]
@cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了

**Comment by cc004** [comment]
> @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了

可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概

**Comment by clacknya** [comment]
> > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> 
> 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概

我倒是买了 2captcha 服务，但最好还是想办法规避 captcha

**Comment by clacknya** [comment]
> > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> 
> 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概

测试了下，非新号用 access_key 登录 sdk 好像就不会出现 captcha 了。另外试了下 v3 和 v1 效果一样

**Comment by WindStill** [comment]
> > > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> > 
> > 
> > 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概
> 
> 测试了下，非新号用 access_key 登录 sdk 好像就不会出现 captcha 了。另外试了下 v3 和 v1 效果一样

access_key的方式怎么使用？

**Comment by clacknya** [comment]
> > > > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> > > 
> > > 
> > > 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概
> > 
> > 
> > 测试了下，非新号用 access_key 登录 sdk 好像就不会出现 captcha 了。另外试了下 v3 和 v1 效果一样
> 
> access_key的方式怎么使用？

对于 v1 来说，通过 username & password 登录后会获取到 access_key，在后面登录可以直接调用 `/api/client/user.info` 用 access_key 获取 uid 和 access_key。只要没过期就能直接登录，过期再通过 username & password 登录。

**Comment by cc004** [comment]
> > > > > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> > > > 
> > > > 
> > > > 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概
> > > 
> > > 
> > > 测试了下，非新号用 access_key 登录 sdk 好像就不会出现 captcha 了。另外试了下 v3 和 v1 效果一样
> > 
> > 
> > access_key的方式怎么使用？
> 
> 对于 v1 来说，通过 username & password 登录后会获取到 access_key，在后面登录可以直接调用 `/api/client/user.info` 用 access_key 获取 uid 和 access_key。只要没过期就能直接登录，过期再通过 username & password 登录。

但是jjc2是有token缓存的，非is_risk情况是不会用户名登录的

**Comment by clacknya** [comment]
> > > > > > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> > > > > 
> > > > > 
> > > > > 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概
> > > > 
> > > > 
> > > > 测试了下，非新号用 access_key 登录 sdk 好像就不会出现 captcha 了。另外试了下 v3 和 v1 效果一样
> > > 
> > > 
> > > access_key的方式怎么使用？
> > 
> > 
> > 对于 v1 来说，通过 username & password 登录后会获取到 access_key，在后面登录可以直接调用 `/api/client/user.info` 用 access_key 获取 uid 和 access_key。只要没过期就能直接登录，过期再通过 username & password 登录。
> 
> 但是jjc2是有token缓存的，非is_risk情况是不会用户名登录的

我指退出后重登，把 access_key 存在配置文件里，过期后再更新

**Comment by cc004** [comment]
> > > > > > > @cc004 有没有 BSGameSDK v3 的 API？感觉 v1 的基本需要验证了
> > > > > > 
> > > > > > 
> > > > > > 可以试一下dev分支的自动过验证码，还没测但是api是能用的（大概
> > > > > 
> > > > > 
> > > > > 测试了下，非新号用 access_key 登录 sdk 好像就不会出现 captcha 了。另外试了下 v3 和 v1 效果一样
> > > > 
> > > > 
> > > > access_key的方式怎么使用？
> > > 
> > > 
> > > 对于 v1 来说，通过 username & password 登录后会获取到 access_key，在后面登录可以直接调用 `/api/client/user.info` 用 access_key 获取 uid 和 access_key。只要没过期就能直接登录，过期再通过 username & password 登录。
> > 
> > 
> > 但是jjc2是有token缓存的，非is_risk情况是不会用户名登录的
> 
> 我指退出后重登，把 access_key 存在配置文件里，过期后再更新

az我想的是应该一段时间呢不会重启机器人吧。。。
