### ISSUE TITLE
验证码链接发不出来

### ISSUE THREAD

**Issue by WindStill** [cc004/pcrjjc2#104]
现在的验证码链接应该是被腾讯过滤了，管理员收不到机器人发的验证码。

```
await bot.send_private_msg(
     # self_id = sid,
    user_id = acinfo['admin'],
    message = f'pcr账号登录需要验证码，请完成以下链接中的验证内容后将第一行validate=后面的内容复制，并用指令/pcrval xxxx将内容发送给机器人完成验证\n验证链接：'
)
```

把message里的 url 去掉，就能收到通知了

**Comment by clacknya** [comment]
tx 有时候会对内容进行风控，需要自己改下格式发

**Comment by WindStill** [comment]
> tx 有时候会对内容进行风控，需要自己改下格式发

老哥，改成什么样的格式

**Comment by clacknya** [comment]
> > tx 有时候会对内容进行风控，需要自己改下格式发
> 
> 老哥，改成什么样的格式

你自己改改用 bot 调用试着发下，每个人可能都不一样，删减/分割之类的都可以试试

**Comment by WindStill** [comment]
> > > tx 有时候会对内容进行风控，需要自己改下格式发
> > 
> > 
> > 老哥，改成什么样的格式
> 
> 你自己改改用 bot 调用试着发下，每个人可能都不一样，删减/分割之类的都可以试试

好的，了解了

**Comment by cc004** [comment]
已缝自动打码 #109
