### ISSUE TITLE
今早4点开始就没有推送了

### ISSUE THREAD

**Issue by along411** [cc004/pcrjjc2#105]

**Comment by along411** [comment]
重启也有验证，但是输完验证之后就查不了竞技场了，消息也不推送，更换游戏帐号也不行，恢复跟删掉version.txt也不顶用了，游戏版本还是4.9.6也没更新啥啊就用不了了

**Comment by along411** [comment]
尝试用了一下7月份的星乃本体可以生效，但是旧版本就没有效果了怎么办

**Comment by cc004** [comment]
当然是不用旧版本
