### ISSUE TITLE
从游戏更新之后发现就不行了，是叔叔换了端口吗？

### ISSUE THREAD

**Issue by zhtyirg3** [cc004/pcrjjc2#108]
![DF72E0DF-E1B6-4BF8-BE94-5F2CAD6CBD56](https://user-images.githubusercontent.com/55908974/203368970-9390991b-5956-4bd6-aeb8-612b50d78af1.png)
大佬，从游戏更新之后发现就不行了，是叔叔换了端口吗？
更新了pcrclient.py，也照样不行，请指导

**Comment by cc004** [comment]
加qq私聊留个账号

**Comment by cc004** [comment]
你先把version.txt删了试试吧

**Comment by cc004** [comment]
已在 #109 中修复

**Comment by zhtyirg3** [comment]
> 已在 #109 中修复

已解决，感谢大佬！
