### ISSUE TITLE
手动过码链接打不开

### ISSUE THREAD

**Issue by ddls14fx** [cc004/pcrjjc2#115]
网页显示
Not Found
The requested URL was not found on this server

**Comment by Ivan737505** [comment]
同样遇到该问题
![Screenshot_2023-05-20-09-19-18-17_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/cc004/pcrjjc2/assets/111074319/65d5c515-5f0c-4af7-889c-ed575d3e6c75)

**Comment by aiyulu1** [comment]
same here
