### ISSUE TITLE
我这边gocq显示请先添加（0）好友是什么原因？

### ISSUE THREAD

**Issue by ycly901** [cc004/pcrjjc2#117]
![@97(Y22LVUGD1_~B28{4R$V](https://github.com/cc004/pcrjjc2/assets/81825867/e77037fd-9a22-4e5d-8180-38e1e80aff10)

**Comment by cc004** [comment]
admin没和机器人加好友或者是单向好友

**Comment by ycly901** [comment]
意思是机器人主人和机器人没加QQ好友导致的？

**Comment by cc004** [comment]
对

**Comment by ycly901** [comment]
看了一下，双方的QQ都是好友了

**Comment by cc004** [comment]
gocq是最新版吗

**Comment by ycly901** [comment]
是的

**Comment by ycly901** [comment]
![)~AM(%@QV($I7ZT$EJ98M`1](https://github.com/cc004/pcrjjc2/assets/81825867/28ca728c-1d04-4ce6-8bcc-3888c755725a)

**Comment by cc004** [comment]
总之感觉是cq问题，摆了（

**Comment by kcn3388** [comment]
[#2143](https://github.com/Mrs4s/go-cqhttp/issues/2143#issuecomment-1555884347)

**Comment by QBL2333** [comment]
刚才遇到这个报错，看了半天发现是更新jjc插件覆盖了原来的account.json没填admin所以默认是0，绷不住了

**Comment by cc004** [comment]
对哦 你没设置qq
