### ISSUE TITLE
手动过码url似乎有些问题，加载不出来验证内容无法完成验证

### ISSUE THREAD

**Issue by kennywang-ubi** [cc004/pcrjjc2#119]
今天遇到如下问题：
验证码连接URL可以正常打开，但是无法加载出验证内容：
![image](https://github.com/cc004/pcrjjc2/assets/78527364/a63e1554-7073-4e87-9671-e65f556d07a4)
报错如下：
![image](https://github.com/cc004/pcrjjc2/assets/78527364/18e2039a-a379-4d22-8ebb-876b81db869d)

**Comment by cc004** [comment]
看到时候验证码已经过期 /pcrval重新获取验证码

**Comment by kcn3388** [comment]
更新新版的
腾讯的网页安全性验证会访问验证码网页导致验证码过期

**Comment by kennywang-ubi** [comment]
> 更新新版的 腾讯的网页安全性验证会访问验证码网页导致验证码过期

感谢，是local captcha这一版吗？刚才试了下就算刷新验证码也要试很多次才会有一次没过期

**Comment by kcn3388** [comment]
24ac961
拼接完成以后直接在浏览器打开，不要发到QQ里

**Comment by cc004** [comment]
可不可以考虑通过ua一类的方法来绕过tx的安全检测
