### ISSUE TITLE
请问出现public_address错误要怎么解决

### ISSUE THREAD

**Issue by dzh666666** [cc004/pcrjjc2#120]
![QQ图片20230529033804](https://github.com/cc004/pcrjjc2/assets/77667512/ebcae4d1-b936-4145-bae3-01e17c9c6376)

**Comment by kcn3388** [comment]
在机器人的配置文件修改/加上IP或者域名配置，如果你的机器人配置文件没问题，应该会有下面三个值：

```python
PORT = 8080  # 本条请保持默认
IP = ''  # 修改为你的服务器ip,推荐修改
public_address = ''  # 修改为你的公网域名,推荐修改
```

**Comment by cc004** [comment]
更新hoshino并使用新的config模板
