### ISSUE TITLE
tw分支中关于msgpack的unpackb方法的问题

### ISSUE THREAD

**Issue by Ryzin** [cc004/pcrjjc2#18]
在pcrclient.py的unpack方法中报错：
msgpack.exceptions.ExtraData: unpack(b) received extra data
我在StackOverflow上查了相关的一些回答，没有办法很好地解决。
比如将msgpack换成umsgpack，或者替换不同msgpack的版本等等。
不过我也注意到requirement.txt限制该依赖在1.0.2版本以上，应该不是版本问题
对代码不是很熟悉，希望能帮忙一下，谢谢

`python
[2021-04-02 11:53:27,435 竞技场推送] INFO: Message 464351974 triggered wrapper by RexTrigger.
C:\Users\Ryzin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2021-04-02 11:53:30,451 竞技场推送] ERROR: <class 'msgpack.exceptions.ExtraData'> occured when wrapper handling message 464351974.
[2021-04-02 11:53:30,451 竞技场推送] ERROR: unpack(b) received extra data.
Traceback (most recent call last):
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\msghandler.py", line 30, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\modules\pcrjjc2\safeservice.py", line 25, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\modules\pcrjjc2\__init__.py", line 103, in on_query_arena
    res = await query(id)
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\modules\pcrjjc2\__init__.py", line 58, in query
    await client.login()
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\modules\pcrjjc2\pcrclient.py", line 151, in login
    await self.callapi('/check/check_agreement', {})
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\modules\pcrjjc2\pcrclient.py", line 127, in callapi
    response = self.unpack(response)[0]
  File "C:\Users\Ryzin\Desktop\PyProject\hoshino_xcw\XCW\hoshino\hoshino\modules\pcrjjc2\pcrclient.py", line 94, in unpack
    return unpackb(dec,
  File "msgpack\_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
`

**Comment by qq1176321897** [comment]
发一下报错时候unpack的内容

**Comment by Ryzin** [comment]
> 发一下报错时候unpack的内容

data = b64decode(data.decode('utf8'))
打印
b"up\x12b\xa7\xcei\xed\xbb\x9c\x93W\x92\x19\xc7-\x04Y\xad\\nl\x9bB)_\xe6`\x84\x19\x01G\xd6]Z\x19\\G);7\xcc\xbd\r\x0c\xbb\x87w\xb7\xf2\xac\xe5`\xff\x1b\xab\x0e@\xe0\x9duD\x03\x99\xbb%\x85y\xa0\xe5\x08-\xfa@\xc3pM\\\xf8\xb3\x8f\x05'\xc9J\xa8t\xefc|:\x80E\x85\xbaB702d476047e1c6c5dd94b925c2301e5a"

dec = aes.decrypt(data[:-32])
打印
b'\x86\xffe=#7_=<me4r\x7f\x81\xa9short_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90\r\r\r\r\r\r\r\r\r\r\r\r\r'

**Comment by Ryzin** [comment]
> 发一下报错时候unpack的内容

unpack方法的入参data
b'WjWvsbQj80h4A23GUC9VvoBp88jctNw/fLuvoVXy19GT2IKUo9AZK1+OPC+GOxKC9M4aWomchk8rXgXRDvSaTkHJhf4PhW/w2lv/rxtu7hxPwHfKs+02zFCa8GZvHmC/N2NiYTZlMmQ5ODhkODUwYTg5NzVhYWFjMmUwNmRmMWQ='

**Comment by qq1176321897** [comment]
> > 发一下报错时候unpack的内容
> 
> data = b64decode(data.decode('utf8'))
> 打印
> b"up\x12b\xa7\xcei\xed\xbb\x9c\x93W\x92\x19\xc7-\x04Y\xad\nl\x9bB)_\xe6`\x84\x19\x01G\xd6]Z\x19\\G);7\xcc\xbd\r\x0c\xbb\x87w\xb7\xf2\xac\xe5`\xff\x1b\xab\x0e@\xe0\x9duD\x03\x99\xbb%\x85y\xa0\xe5\x08-\xfa@\xc3pM\\xf8\xb3\x8f\x05'\xc9J\xa8t\xefc|:\x80E\x85\xbaB702d476047e1c6c5dd94b925c2301e5a"
> 
> dec = aes.decrypt(data[:-32])
> 打印
> b'\x86\xffe=#7_=<me4r\x7f\x81\xa9short_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90\r\r\r\r\r\r\r\r\r\r\r\r\r'

啊 这看起来是aes没有删除padding呢

**Comment by clacknya** [comment]
from Crypto.Util.Padding import unpad

unpackb(unpad(decrypted, 16))

**Comment by qq1176321897** [comment]
不过感觉这样没办法解决问题呢，即使unpad过了这个格式也不大对 我觉得这个如果是`b'\x86\xaashort_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce\x60f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90'`的话才是可以读的 感觉可能是服务端的问题吧，你可以试试把这个unpack改成try...unpack...except null 毕竟这个解包失败也不影响其他代码

**Comment by clacknya** [comment]
建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。

**Comment by qq1176321897** [comment]
> 建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。

这个应该没有问题 \xcc是表示uint8 \xd1是result_code的值209 \xa4是data的前缀 \x90是空array 应该没啥问题。。。

**Comment by qq1176321897** [comment]
> 建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。

这个应该没有问题 \xcc是表示uint8 \xd1是result_code的值209 \xa4是data的前缀 \x90是空array 应该没啥问题。。。

**Comment by qq1176321897** [comment]
> > 建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。
> 
> 这个应该没有问题 \xcc是表示uint8 \xd1是result_code的值209 \xa4是data的前缀 \x90是空array 应该没啥问题。。。

不过能看出来result code不是1似乎有问题。。。要不要看看是不是之前的请求就有result code不等于1的情况

**Comment by clacknya** [comment]
code 209 是 请求体解析失败 的意思

**Comment by Ryzin** [comment]
> 建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。


> crypted
> b"\n\x15v)\xf1\xb7>x\x86\xd48\xc9\xde\x92\xdb3\x91!\x88\xb8\xfc\x8d\x8ej\xe3\x08\x02\xe0Px\xa5h1\xf0{\x18['\x145\xf5\x8c\x06\xcfoU\xfb\xf4o\xdb\xf8\xbc\xa9\xf1\x85\xf9\xbbg\xe0\xc0\xc6\xc4g\x06\xf3\xaee\xda\xea\x94b\x80H.\xd8_3\x88Y\x907afaa3b6f882529d83f62acb591b1ed2"
> header
> {'Accept-Encoding': 'gzip', 'User-Agent': 'Dalvik/2.1.0 (Linux, U, Android 5.1.1, PCRT00 Build/LMY48Z)', 'Content-Type': 'application/octet-stream', 'Expect': '100-continue', 'X-Unity-Version': '2018.4.21f1', 'APP-VER': '2.5.1', 'BATTLE-LOGIC-VERSION': '4', 'BUNDLE-VER': '', 'DEVICE': '2', 'DEVICE-ID': '7b1703a5d9b394e24051d7a5d4818f17', 'DEVICE-NAME': 'OPPO PCRT00', 'GRAPHICS-DEVICE-NAME': 'Adreno (TM) 640', 'IP-ADDRESS': '10.0.2.15', 'KEYCHAIN': '', 'LOCALE': 'Jpn', 'PLATFORM-OS-VERSION': 'Android OS 5.1.1 / API-22 (LMY48Z/rel.se.infra.20200612.100533)', 'REGION-CODE': '', 'RES-VER': '00017004', 'SID': '3814e73d360334f28f48b6329f877331', 'platform': '4', 'PARAM': '3d94529ea67d427bff78648e6652633fcab3b331', 'SHORT-UDID': '000996B505A076:960B792;611:555;634>376;153934884746508685537021360082586'}
> proxy
> {'http': 'localhost:7890', 'https': 'localhost:7890', 'ftp': 'ftp://127.0.0.1:7890'}
> response = await resp.content
> b'ETdskr56FnrjdWt04bQ0O9IpsyDek0oBYCMnhi4rKhX8hjj+heIx4UqAjHsDaxU98pkCP0yG8hVO/j3gTDW1l6IWswBOwozDmEGfVeEdZ0uaIjX4+A+PcbhAb1ncBGqDNGRmZGMwY2RhYzc2NjZmYjI0Y2EyYmU3ZDM1YmI5NDY='

**Comment by qq1176321897** [comment]
> > 建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。
> 
> > crypted
> > b"\n\x15v)\xf1\xb7>x\x86\xd48\xc9\xde\x92\xdb3\x91!\x88\xb8\xfc\x8d\x8ej\xe3\x08\x02\xe0Px\xa5h1\xf0{\x18['\x145\xf5\x8c\x06\xcfoU\xfb\xf4o\xdb\xf8\xbc\xa9\xf1\x85\xf9\xbbg\xe0\xc0\xc6\xc4g\x06\xf3\xaee\xda\xea\x94b\x80H.\xd8_3\x88Y\x907afaa3b6f882529d83f62acb591b1ed2"
> > header
> > {'Accept-Encoding': 'gzip', 'User-Agent': 'Dalvik/2.1.0 (Linux, U, Android 5.1.1, PCRT00 Build/LMY48Z)', 'Content-Type': 'application/octet-stream', 'Expect': '100-continue', 'X-Unity-Version': '2018.4.21f1', 'APP-VER': '2.5.1', 'BATTLE-LOGIC-VERSION': '4', 'BUNDLE-VER': '', 'DEVICE': '2', 'DEVICE-ID': '7b1703a5d9b394e24051d7a5d4818f17', 'DEVICE-NAME': 'OPPO PCRT00', 'GRAPHICS-DEVICE-NAME': 'Adreno (TM) 640', 'IP-ADDRESS': '10.0.2.15', 'KEYCHAIN': '', 'LOCALE': 'Jpn', 'PLATFORM-OS-VERSION': 'Android OS 5.1.1 / API-22 (LMY48Z/rel.se.infra.20200612.100533)', 'REGION-CODE': '', 'RES-VER': '00017004', 'SID': '3814e73d360334f28f48b6329f877331', 'platform': '4', 'PARAM': '3d94529ea67d427bff78648e6652633fcab3b331', 'SHORT-UDID': '000996B505A076:960B792;611:555;634>376;153934884746508685537021360082586'}
> > proxy
> > {'http': 'localhost:7890', 'https': 'localhost:7890', 'ftp': 'ftp://127.0.0.1:7890'}
> > response = await resp.content
> > b'ETdskr56FnrjdWt04bQ0O9IpsyDek0oBYCMnhi4rKhX8hjj+heIx4UqAjHsDaxU98pkCP0yG8hVO/j3gTDW1l6IWswBOwozDmEGfVeEdZ0uaIjX4+A+PcbhAb1ncBGqDNGRmZGMwY2RhYzc2NjZmYjI0Y2EyYmU3ZDM1YmI5NDY='

发一下udid udid被作为aes加密的密钥

**Comment by Ryzin** [comment]
> 不过感觉这样没办法解决问题呢，即使unpad过了这个格式也不大对 我觉得这个如果是`b'\x86\xaashort_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce\x60f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90'`的话才是可以读的 感觉可能是服务端的问题吧，你可以试试把这个unpack改成try...unpack...except null 毕竟这个解包失败也不影响其他代码



> > > 建议发下完整的请求和响应，看这个响应后面是 `result_code\xcc\xd1\xa4data\x90` ，明显有数据被截断了。猜测没有接收到完整数据。
> > 
> > 
> > > crypted
> > > b"\n\x15v)\xf1\xb7>x\x86\xd48\xc9\xde\x92\xdb3\x91!\x88\xb8\xfc\x8d\x8ej\xe3\x08\x02\xe0Px\xa5h1\xf0{\x18['\x145\xf5\x8c\x06\xcfoU\xfb\xf4o\xdb\xf8\xbc\xa9\xf1\x85\xf9\xbbg\xe0\xc0\xc6\xc4g\x06\xf3\xaee\xda\xea\x94b\x80H.\xd8_3\x88Y\x907afaa3b6f882529d83f62acb591b1ed2"
> > > header
> > > {'Accept-Encoding': 'gzip', 'User-Agent': 'Dalvik/2.1.0 (Linux, U, Android 5.1.1, PCRT00 Build/LMY48Z)', 'Content-Type': 'application/octet-stream', 'Expect': '100-continue', 'X-Unity-Version': '2018.4.21f1', 'APP-VER': '2.5.1', 'BATTLE-LOGIC-VERSION': '4', 'BUNDLE-VER': '', 'DEVICE': '2', 'DEVICE-ID': '7b1703a5d9b394e24051d7a5d4818f17', 'DEVICE-NAME': 'OPPO PCRT00', 'GRAPHICS-DEVICE-NAME': 'Adreno (TM) 640', 'IP-ADDRESS': '10.0.2.15', 'KEYCHAIN': '', 'LOCALE': 'Jpn', 'PLATFORM-OS-VERSION': 'Android OS 5.1.1 / API-22 (LMY48Z/rel.se.infra.20200612.100533)', 'REGION-CODE': '', 'RES-VER': '00017004', 'SID': '3814e73d360334f28f48b6329f877331', 'platform': '4', 'PARAM': '3d94529ea67d427bff78648e6652633fcab3b331', 'SHORT-UDID': '000996B505A076:960B792;611:555;634>376;153934884746508685537021360082586'}
> > > proxy
> > > {'http': 'localhost:7890', 'https': 'localhost:7890', 'ftp': 'ftp://127.0.0.1:7890'}
> > > response = await resp.content
> > > b'ETdskr56FnrjdWt04bQ0O9IpsyDek0oBYCMnhi4rKhX8hjj+heIx4UqAjHsDaxU98pkCP0yG8hVO/j3gTDW1l6IWswBOwozDmEGfVeEdZ0uaIjX4+A+PcbhAb1ncBGqDNGRmZGMwY2RhYzc2NjZmYjI0Y2EyYmU3ZDM1YmI5NDY='
> 
> 发一下udid udid被作为aes加密的密钥

> 4a3dc201-a8e4-49b7-a87e-c0423b32acfc

**Comment by clacknya** [comment]
看了下感觉是 IV 出了问题。构造了个正常的响应，再 packb 后得到的是
```
b'\x81\xacdata_headers\x86\xaashort_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x80'
```
这与上面的响应
```
b'\x86\xffe=#7_=<me4r\x7f\x81\xa9short_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90'
```
只有第一个 16bit 不同，根据 CBC 的性质，猜测是 IV 出了问题。
没有研究过台服客户端，不清楚具体有什么不一样。

**Comment by Ryzin** [comment]
> 看了下感觉是 IV 出了问题。构造了个正常的响应，再 packb 后得到的是
> 
> ```
> b'\x81\xacdata_headers\x86\xaashort_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x80'
> ```
> 
> 这与上面的响应
> 
> ```
> b'\x86\xffe=#7_=<me4r\x7f\x81\xa9short_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90'
> ```
> 
> 只有第一个 16bit 不同，根据 CBC 的性质，猜测是 IV 出了问题。
> 没有研究过台服客户端，不清楚具体有什么不一样。

好吧，我几乎没怎么涉及过加密方面的知识，没啥进展我还是弃坑了。感谢大佬的耐心回复

**Comment by qq1176321897** [comment]
> 看了下感觉是 IV 出了问题。构造了个正常的响应，再 packb 后得到的是
> 
> ```
> b'\x81\xacdata_headers\x86\xaashort_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x80'
> ```
> 
> 这与上面的响应
> 
> ```
> b'\x86\xffe=#7_=<me4r\x7f\x81\xa9short_udid\xce3\xe7\x82\x1d\xa9viewer_id\xc0\xa3sid\xa0\xaaservertime\xce`f\x98\x18\xabresult_code\xcc\xd1\xa4data\x90'
> ```
> 
> 只有第一个 16bit 不同，根据 CBC 的性质，猜测是 IV 出了问题。
> 没有研究过台服客户端，不清楚具体有什么不一样。

嗯 你说得对

**Comment by qq1176321897** [comment]
最后发现是台服分服处理错误导致服务器没有找到对应的udid从而返回的iv不对（因为iv由udid对应） 在 98d1dc83bfc79e45ef8bb5b7034e81d95d3acb0f 中已经修复，现在会报错code=204是由于版本不对，你可以根据现在台服版本更改一下appver的版本

**Comment by Ryzin** [comment]
> 最后发现是台服分服处理错误导致服务器没有找到对应的udid从而返回的iv不对（因为iv由udid对应） 在 [98d1dc8](https://github.com/qq1176321897/pcrjjc2/commit/98d1dc83bfc79e45ef8bb5b7034e81d95d3acb0f) 中已经修复，现在会报错code=204是由于版本不对，你可以根据现在台服版本更改一下appver的版本

蛤，拉了新代码后
>  pcrclient: /check/check_agreement api called
>  pcrclient: /check/game_start api called
>  pcrclient: /load/index api failed code = 205, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}

**Comment by qq1176321897** [comment]
> > 最后发现是台服分服处理错误导致服务器没有找到对应的udid从而返回的iv不对（因为iv由udid对应） 在 [98d1dc8](https://github.com/qq1176321897/pcrjjc2/commit/98d1dc83bfc79e45ef8bb5b7034e81d95d3acb0f) 中已经修复，现在会报错code=204是由于版本不对，你可以根据现在台服版本更改一下appver的版本
> 
> 蛤，拉了新代码后
> 
> > pcrclient: /check/check_agreement api called
> > pcrclient: /check/game_start api called
> > pcrclient: /load/index api failed code = 205, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\n即將返回標題畫面。'}

啊 这 你要不要试试修改一下platform的值，，在pcrclient的__init__里面 试试0 1 2 3

**Comment by lulu666lulu** [comment]
这是msgpack的锅吧（

**Comment by Ryzin** [comment]
> > > 最后发现是台服分服处理错误导致服务器没有找到对应的udid从而返回的iv不对（因为iv由udid对应） 在 [98d1dc8](https://github.com/qq1176321897/pcrjjc2/commit/98d1dc83bfc79e45ef8bb5b7034e81d95d3acb0f) 中已经修复，现在会报错code=204是由于版本不对，你可以根据现在台服版本更改一下appver的版本
> > 
> > 
> > 蛤，拉了新代码后
> > > pcrclient: /check/check_agreement api called
> > > pcrclient: /check/game_start api called
> > > pcrclient: /load/index api failed code = 205, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\n即將返回標題畫面。'}
> 
> 啊 这 你要不要试试修改一下platform的值，，在pcrclient的__init__里面 试试0 1 2 3

试过了，那样只会连第一个请求都不行

**Comment by qq1176321897** [comment]
> 这是msgpack的锅吧（

msgpack的都修了（
问题是代码没写205是什么错误码啊（

**Comment by lulu666lulu** [comment]
205（
我忘了

**Comment by lulu666lulu** [comment]
我最早搞台服的时候就是205卡了快半年（

**Comment by lulu666lulu** [comment]
然后你干了啥就好了（

**Comment by Ryzin** [comment]
测试账号
322694755
Tlb51003289

**Comment by lulu666lulu** [comment]
我又没下台服
你发这个额有个der用

**Comment by Ryzin** [comment]
> 我又没下台服
> 你发这个额有个der用

呀咯

**Comment by cc004** [comment]
自动close大失败
