### ISSUE TITLE
tw

### ISSUE THREAD

**Issue by BlackTitle** [cc004/pcrjjc2#34]
TW分支登录报错205。。。标题一不小心按到回车了没打全。
`[2021-06-02 20:21:36,131 nonebot] INFO: Self: 471425760, Message 1696779255 from
 2775116592@[群:792730444]: '竞技场查询 259356212'
[2021-06-02 20:21:36,132 竞技场推送] INFO: Message 1696779255 triggered wrapper
by RexTrigger.
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\
urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request
 is being made to host 'localhost'. Adding certificate verification is strongly
advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-w
arnings
  warnings.warn(
pcrclient: /check/check_agreement api called
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\
urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request
 is being made to host 'localhost'. Adding certificate verification is strongly
advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-w
arnings
  warnings.warn(
pcrclient: /check/game_start api called
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\
urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request
 is being made to host 'localhost'. Adding certificate verification is strongly
advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-w
arnings
  warnings.warn(
pcrclient: /load/index api failed code = 205, {'status': 3, 'title': '伺服器錯誤
', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}`
这是错误代码

**Comment by cc004** [comment]
？

**Comment by BlackTitle** [comment]
我操，好快的速度

**Comment by cc004** [comment]
这个我也不知道咋回事，我没那么多账号去测试台123的header，不过目前看来就是改子域名和platform id

**Comment by cc004** [comment]
自动close大失败
