### ISSUE TITLE
能否实现竞技场锁人界面就提醒？

### ISSUE THREAD

**Issue by yfsunrise** [cc004/pcrjjc2#35]
被点了就播报

**Comment by Kyaru2333** [comment]
机器人在同场的时候应该就可以

**Comment by yfsunrise** [comment]
能提供下思路吗，是查询的哪个参数？

**Comment by Kyaru2333** [comment]
你不如一直锁住自己吧，这样多好

**Comment by yfsunrise** [comment]
都10分钟了怎么锁嘛，今天看见有能报被锁的bot，想研究下咋实现的

**Comment by yfsunrise** [comment]
@cc004 您好，今天看到个bot可以被人锁就播报，提示jjc/pjjc 空闲标识状态 已被选中，想知道这是通过什么实现的，是跟名次一起查询的其他参数吗？

**Comment by cc004** [comment]
不知道
