### ISSUE TITLE
切换到Notice-all后持续报错

### ISSUE THREAD

**Issue by cadaeibf1** [cc004/pcrjjc2#52]
切换到notice-all后，再次进行竞技场查询，bot会提示“查询出错，发生了错误。\n回到标题界面。”

bot界面提示信息如图
![QQ截图20211014015007](https://user-images.githubusercontent.com/65361365/137186805-c1b79bdf-a6e0-43ab-9c14-c0c859d4334e.png)

不知道是什么问题呢……

**Comment by cc004** [comment]
这auto close就是不好使，fixed in 854393f82d98c95cea9a965205866bbd5c56a8f4
