### ISSUE TITLE
查询失败了，麻烦大佬看看

### ISSUE THREAD

**Issue by zhtyirg3** [cc004/pcrjjc2#54]
今天安装了插件，发现机器人没有发送验证码给管理员。
查询失败。麻烦大佬看看是哪一步出问题了
![QWJI6KKJH5J{FH{SN`9Z 37](https://user-images.githubusercontent.com/55908974/144019300-8444b48e-3e8c-4ac9-830f-937dd717eedd.png)

**Comment by cc004** [comment]
按照requirements.txt回退msgpack版本

**Comment by zhtyirg3** [comment]
> 

可以了，谢谢大佬
