### ISSUE TITLE
发生了错误，返回标题界面

### ISSUE THREAD

**Issue by WindStill** [cc004/pcrjjc2#56]
大佬，帮忙看下。

![image](https://user-images.githubusercontent.com/958456/147021541-317629a9-cfa8-43f1-b911-bb7201c9c174.png)

**Comment by aiyulu1** [comment]
更新 pcrclient.py 文件里的
    'APP-VER' : '3.4.10',
为
    'APP-VER' : '3.4.11',

**Comment by WindStill** [comment]
> 更新 pcrclient.py 文件里的 'APP-VER' : '3.4.10', 为 'APP-VER' : '3.4.11',

好的，多谢。解决了
