### ISSUE TITLE
pcrjjc2从老版本升级到新版本报错，回滚也不行，是依赖出了问题么

### ISSUE THREAD

**Issue by 1529960009** [cc004/pcrjjc2#66]
![QQ截图20220225100406](https://user-images.githubusercontent.com/45947734/155640906-7be004e8-75a0-41e4-bcc5-b655afa984f0.png)

**Comment by CYDXDianXian** [comment]
依赖问题，我这里测试是msgpack版本更新到1.0.3版所致，需要将msgpack回滚到1.0.2版本，按如下方法操作：
```
pip uninstall msgpack

pip install msgpack==1.0.2
```

**Comment by CYDXDianXian** [comment]
现在你那边正常了么，如果还有问题欢迎继续反馈~

**Comment by 1529960009** [comment]
正常了，谢谢大佬

**Comment by CYDXDianXian** [comment]
> 正常了，谢谢大佬

ok，正常了就好，不用谢~~
