### ISSUE TITLE
无法切换到notice-all

### ISSUE THREAD

**Issue by 1529960009** [cc004/pcrjjc2#67]
![企业微信截图_20220226102252](https://user-images.githubusercontent.com/45947734/155825214-65d43d32-6c6e-4509-9607-f9281e01cd52.png)

**Comment by cc004** [comment]
因为我之前force push把分支弄炸了
为了遮丑就把分支整个删了
你可以请电线佬重做一下（

**Comment by 1529960009** [comment]
好像自己加几行也能实习上升效果，不用麻烦大佬了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月26日(周六) 晚上10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cc004/pcrjjc2] 无法切换到notice-all (Issue #67)




 
因为我之前force push把分支弄炸了
 为了遮丑就把分支整个删了
 你可以请电线佬重做一下（

**Comment by CYDXDianXian** [comment]
> 好像自己加几行也能实习上升效果，不用麻烦大佬了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月26日(周六) 晚上10:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cc004/pcrjjc2] 无法切换到notice-all (Issue #67) 因为我之前force push把分支弄炸了 为了遮丑就把分支整个删了 你可以请电线佬重做一下（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

把__init__.py中的308行314行的>改成!=就行了：
```
            if res[0] != last[0] and info['arena_on']:

            if res[1] != last[1] and info['grand_arena_on']:
```

**Comment by CYDXDianXian** [comment]
notice-all分支已创建
