### ISSUE TITLE
SafeService报错

### ISSUE THREAD

**Issue by SonderXiaoming** [cc004/pcrjjc2#69]
报错代码Execution of job "SafeService.decoWrapper.<locals>.wrapper (trigger: interval[0:01:00], next run at: 2022-02-28 01:05:10 CST)" skipped: maximum number of running instances reached (1)
重启好像暂时会好
也可能是其他插件的问题，但好像就这个插件不能用
改成星乃的Service就没问题了

**Comment by CYDXDianXian** [comment]
稍等，正在退回设置。。。合并分支出问题了（

**Comment by CYDXDianXian** [comment]
修改已经被退回，功能回复正常

**Comment by WindStill** [comment]
现在最新版本又有这个问题了
