### ISSUE TITLE
更新版本号之后，出现错误。

### ISSUE THREAD

**Issue by zhtyirg3** [cc004/pcrjjc2#91]
![1](https://user-images.githubusercontent.com/55908974/168501269-ec8643c6-fb35-4754-a2a7-fa958f6adde6.jpg)
![2](https://user-images.githubusercontent.com/55908974/168501280-2e8e9fa2-5cc4-4a13-aa5f-fca8fae3c6cd.jpg)
![3](https://user-images.githubusercontent.com/55908974/168501302-cf4dd21e-20b3-4c8b-8c97-ac04c73a3047.jpg)
更新后发现故障了，然后编辑一下pcrclient.py里面的版本号，发现还是出现问题，请问大佬，这是什么问题？

**Comment by zhtyirg3** [comment]
后来修改了 version.txt版本号可以，可以正常查询到排名，但是还是会出现1、2图的错误。

**Comment by hot36952** [comment]
> 

你好，我也碰到这个问题，请问version.txt版本号修改成什么才可以？

**Comment by shadow7755** [comment]
我的建议是删除了，重新从git clone。我昨天也报一样的错，然后删了文件夹重新clone就好了。

**Comment by zhtyirg3** [comment]
> 我的建议是删除了，重新从git clone。我昨天也报一样的错，然后删了文件夹重新clone就好了。

还是没用，一样的错误。虽然还是能用，但是真的逼死强迫症。

**Comment by clacknya** [comment]
你把 .b 删了吧，其实你改成 9.9.9 也能用的

**Comment by zhtyirg3** [comment]
> 你把 .b 删了吧，其实你改成 9.9.9 也能用的
> 
> 2 的错误应该是有重复加载了
> 
> 错误 3 有时候是会出现，可能和服务端有关吧

重复加载？没有找到什么原因，哭了，现在隔一段时间就卡死一次

**Comment by azmiao** [comment]
图一是hoshino版本问题，新版hoshino不需要元组，旧版必须元组，请更新Hoshino的Service，如不想更新可以将prefix前缀参数改成元组形式，即加一个括号，形如
'''
@on_prefix(('xxx', 'xxx', 'xxx'))
'''
