### ISSUE TITLE
平均一天一次验证码输入正常吗

### ISSUE THREAD

**Issue by Houraisan-yume** [cc004/pcrjjc2#95]
平均一天左右就要不定时弹一次geetest，现在为止换了三个pcr号，换一个能顶几天不用输入，然后某天需要验证后就开始稳定一天一次验证。。。
想问下这个频繁验证是正常的吗，还是单纯的账号或者ip风控问题。
不定时弹验证，不验证就检查不了排名还是挺烦人的。。。

**Comment by CYDXDianXian** [comment]
单个账号长时间使用就会出现这样的问题，这属于正常现象，如果不想频繁输入验证码可以多准备几个pcr新号。听说还可以自行连接打码平台，自动打验证码（虽然我不会-.-）

**Comment by cc004** [comment]
https://github.com/watermellye/farm/blob/6c3f9a0fb5149958b1b3662d557f93d33d599c95/__init__.py#L109-L180

**Comment by fgo000000** [comment]
嫌麻烦可以试试给小号充一块钱

**Comment by Houraisan-yume** [comment]
> fgo000000
真就不弹了，这就是氪金的力量吗（

**Comment by cc004** [comment]
已缝自动打码 #109
