### ISSUE TITLE
能否添加同时监控多人的功能

### ISSUE THREAD

**Issue by Baninn** [cc004/pcrjjc2#97]
目前一个QQ号只能绑定一个ID，如果想查看其他的号就只能手动查询。请问能否实现一个号同时监控多人的功能

**Comment by CYDXDianXian** [comment]
### 暂不考虑增加该功能，如有需要可自行魔改
- 考虑到大部分人的服务器承载能力有限，该功能会成倍增加服务器负载。若还使用了代理，代理流量用量也会成倍增加。
- 多人监控还需更改binds.json文件的账号数据架构，故属于魔改，更新后旧数据无法继承，只能删除旧数据后让全部使用者重新绑定账号，这种断层式更新不利于维护者维护bot，建议fork本库后另行魔改。

**Comment by Baninn** [comment]
感谢说明。已fork notice-all分支并简单魔改了一下https://github.com/Baninn/pcrjjc2/tree/notice-all
